/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./app/Models/*.php",
  ],
  safelist: [
    'border-l-4',
    'border-l-accent',
    'border-l-amber-600',
    'border-l-primary',
    'border-l-success',
    'border-l-borderc',
    'text-accent',
    'bg-red-50',
    'text-amber-700',
    'bg-amber-50',
    'text-primary',
    'bg-blue-50',
    'text-success',
    'bg-emerald-50',
    'text-textsub',
    'bg-slate-100',
    'bg-rose-50',
    'text-rose-600',
    'border-rose-200',
    'bg-rose-500',
    'bg-amber-500',
    'border-amber-200',
    'bg-blue-600',
    'border-blue-200',
    'bg-emerald-500',
    'border-emerald-200',
    'bg-emerald-50/40',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: '#3B82F6',
        secondary: '#6366f1',
        accent: '#EF4444',
        warning: '#F59E0B',
        success: '#10B981',
        bg: '#f9f9ff',
        surface: '#ffffff',
        borderc: '#d8d9e3',
        textmain: '#1b1b1f',
        textsub: '#44474e',
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.15', fontWeight: '800' }],
        'title-md': ['18px', { lineHeight: '1.4', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.3', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '4px',
        card: '4px',
      },
    },
  },
  plugins: [],
}
